const ActionTypes = {
 GET_ALL_CROP:'GET_ALL_CROP',
 SPECIFIC_CROP:'SPECIFIC_CROP',
 GET_ALL_PROBLEM:'GET_ALL_PROBLEM',
 SPECIFIC_PROBLEM:'SPECIFIC_PROBLEM',
 LOADER_PROCESS:'LOADER_PROCESS',
 LOADER_UN_PROCESS:'LOADER_UN_PROCESS'
}

export default ActionTypes;