const ActionTypes = {
    ADD_FERTILIZER:'ADD_FERTILIZER',
    ADD_PESTICIDE:'ADD_PESTICIDE',
    ADD_MACHINERY:'ADD_MACHINERY',
    GET_FERTILIZER:'GET_FERTILIZER',
    GET_MACHINERY:'GET_MACHINERY',
    GET_PESTICIDE:'GET_PESTICIDE',
    UPDATE_FERTILIZER:'UPDATE_FERTILIZER',
    UPDATE_MACHINERY:'UPDATE_MACHINERY',
    UPDATE_PESTICIDE:'UPDATE_PESTICIDE',
    GET_ALL_FERTILIZER:'GET_ALL_FERTILIZER',
    GET_ALL_PESTICIDE:'GET_ALL_PESTICIDE',
    GET_ALL_MACHINERY:'GET_ALL_MACHINERY',
    GET_SPECIFIC_FERTILIZER:'GET_SPECIFIC_FERTILIZER',
    GTE_SPECIFIC_PESTICIDE:'GET_SPECIFIC_PESTICIDE',
    GET_SPECIFIC_MACHINERY:'GET_SPECIFIC_MACHINERY',
    STORE_FOR_MSG:'STORE_FOR_MSG',
    PROCESS_PROGRESS:'PROCESS_PROGRESS',
    PROCESS_DONE:'PROCESS_DONE',
    ERROR_MESSAGE:'ERROR_MESSAGE',
    ERROR_NULL:'ERROR_NULL',
    DELETE_MACHINERY:'DELETE_MACHINERY',
    DELETE_FERTILIZER:'DELETE_FERTILIZER',
    DELETE_PESTICIDE:'DELETE_PESTICIDE'
}

export default ActionTypes;