const ActionTypes = {
    ADD_FERTILIZER:'ADD_FERTILIZER',
    ADD_PESTICIDE:'ADD_PESTICIDE',
    ADD_MACHINERY:'ADD_MACHINERY',
    GET_FERTILIZER:'GET_FERTILIZER',
    GET_MACHINERY:'GET_MACHINERY',
    GET_PESTICIDE:'GET_PESTICIDE',
    UPDATE_FERTILIZER:'UPDATE_FERTILIZER',
    UPDATE_MACHINERY:'UPDATE_MACHINERY',
    UPDATE_PESTICIDE:'UPDATE_PESTICIDE',
    GET_ALL_FERTILIZER:'GET_ALL_FERTILIZER',
    GET_ALL_PESTICIDE:'GET_ALL_PESTICIDE',
    GET_ALL_MACHINERY:'GET_ALL_MACHINERY'
}

export default ActionTypes;