const ActionTypes = {
    MENU: 'MENU',
    CHANGE:'CHANGE',
    OPEN:'OPEN',
    AUTH_ERROR:'AUTH_ERROR',
    AUTH_USER:'AUTH_USER',
    FETCH_MESSAGE:'FETCH_MESSAGE',
    UNAUTH_USER:'UNAUTH_USER',
    AUTH_PROCESS:'AUTH_PROCESS',
    WEATHER_GET:'WEATHER_GET',
    LOAD_STORE_STATE:'LOAD_STORE_STATE',
    GET_CONNECT:'GET_CONNECT',
    UN_AUTH_PROCESS:'UN_AUTH_PROCESS',
    EMAIL_SEND:'EMAIL_SEND',
    EMAIL_EMPTY:'EMAIL_EMPTY'
  
  }
  
  export default ActionTypes;
  