const ActionTypes = {
  GET_CROP_SPECIFIC: 'GET_CROP',
  GET_PROBLEM_SPECIFIC:'GET_PROBLEM',
  UPDATE_CROP:'UPDATE_CROP',
  UPDATE_PROBLEM:'UPDATE_PROBLEM',
  ADD_CROP:'ADD_CROP',
  ADD_PROBLEM:'ADD_PROBLEM',
  DELETE_CROP:'DELETE_CROP',
  DELETE_PROBLEM:'DELETE_PROBLEM',
  NOTIFICATION_CROP:'NOTIFICATION_CROP',
 
  PROCESS_PROGRESS:'PROCESS_PROGRESS',
  PROCESS_DONE:'PROCESS_DONE',
  ERROR_MESSAGE:'ERROR_MESSAGE',
  ERROR_NULL:'ERROR_NULL',
  NOTIFICATION_PROBLEM:'NOTIFICATION_PROBLEM',
  NOTIFICATION_CROP:'NOTIFICATION_CROP',
  ALL_CITY_LIST:'ALL_CITY_LIST'
}

export default ActionTypes;
