const ActionTypes = {
  GET_CROP_SPECIFIC: 'GET_CROP',
  GET_PROBLEM_SPECIFIC:'GET_PROBLEM',
  UPDATE_CROP:'UPDATE_CROP',
  UPDATE_PROBLEM:'UPDATE_PROBLEM',
  ADD_CROP:'ADD_CROP',
  ADD_PROBLEM:'ADD_PROBLEM',
  DELETE_CROP:'DELETE_CROP',
  DELETE_PROBLEM:'DELETE_PROBLEM'
}

export default ActionTypes;
