const ActionTypes = {
    GET_ALL_MESSAGE:'GET_ALL_MESSAGE',
    GET_ALL_SPECIFIC:'GET_ALL_SPECIFIC',
    LISTEN_MESSAGE:'LISTEN_MESSAGE',
    START_MESSAGE:'START_MESSAGE',
    LOAD_PROCESS:'LOAD_PROCESS',
    LOAD_DONE:'LOAD_DONE'
    // GET_
}
export default ActionTypes;