const ActionTypes = {
    GET_ALL_MESSAGE:'GET_ALL_MESSAGE',
    GET_ALL_SPECIFIC:'GET_ALL_SPECIFIC',
    LISTEN_MESSAGE:'LISTEN_MESSAGE',
    START_MESSAGE:'START_MESSAGE'
    // GET_
}
export default ActionTypes;